#ifndef __DIALOGS_H__
#define __DIALOGS_H__

#include "wx/wx.h"

/*ID_OBJ_DIALOG-NAME*/
enum DialogEnum{
	ID_TEXT_VERSION = 10000,
	ID_TEXT_THICKNESS,
	ID_SLIDER_THICKNESS,
	ID_TEXT_COLOR,
	ID_RADIOBOX_COLOR,
	ID_TEXT_TRIANGLE,
	ID_LISTBOX_TRIANGLE,
	ID_PROPERTIES_TRIANGLE,
	ID_DELETE_TRIANGLE,
	ID_TEXT_TRIANGLE_PROPERTIES,
	ID_TRIANGLE_PROPERTIES,
	ID_THICKNESS_PROPERTIES,
	ID_TEXT_THICKNESS_PROPERTIES,
	ID_SPINCTRL_PROPERTIES,
	ID_RADIOBOX_COLOR_PROPERTIES
};

#endif